version: 0.0
os: linux
files:
  - source: projects/
    destination: /home/ubuntu/projects
permissions:
  - object: /home/ubuntu/
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 755
    type:
      - file
  - object: /home/ubuntu
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 644
    type:
      - directory   
hooks:
    BeforeInstall:
      - location: scripts/remove.sh
    AfterInstall:
      - location: scripts/post.sh
     